import axios, { AxiosInstance } from "axios";

const BASE_URL = "https://api.tella.com/v1";

export interface Video {
  id: string;
  name: string;
  description?: string;
  duration?: number;
  views?: number;
  created_at: string;
  updated_at: string;
  view_link?: string;
  embed_link?: string;
  playlist_id?: string;
  thumbnail_url?: string;
  transcript?: string;
}

export interface Playlist {
  id: string;
  name: string;
  description?: string;
  video_count?: number;
  created_at: string;
}

export interface Webhook {
  id: string;
  url: string;
  events: string[];
  created_at: string;
  signing_secret?: string;
}

export interface ZoomAnnotation {
  video_id: string;
  timestamp_seconds: number;
  x: number;
  y: number;
  zoom_level: number;
  label?: string;
}

export class TellaClient {
  private http: AxiosInstance;
  // In-memory zoom annotation store (persisted per server session)
  private zoomAnnotations: Map<string, ZoomAnnotation[]> = new Map();

  constructor(apiKey: string) {
    this.http = axios.create({
      baseURL: BASE_URL,
      headers: {
        Authorization: `Bearer ${apiKey}`,
        "Content-Type": "application/json",
      },
      timeout: 15000,
    });
  }

  // ── Videos ──────────────────────────────────────────────────────────────

  async listVideos(params: {
    cursor?: string;
    limit?: number;
    playlist_id?: string;
  }): Promise<{ videos: Video[]; next_cursor?: string }> {
    const { data } = await this.http.get("/videos", { params });
    return data;
  }

  async getVideo(videoId: string): Promise<Video> {
    const { data } = await this.http.get(`/videos/${videoId}`);
    return data;
  }

  // ── Playlists ────────────────────────────────────────────────────────────

  async listPlaylists(): Promise<Playlist[]> {
    const { data } = await this.http.get("/playlists");
    return Array.isArray(data) ? data : data.playlists ?? [];
  }

  // ── Webhooks ─────────────────────────────────────────────────────────────

  async listWebhooks(): Promise<Webhook[]> {
    const { data } = await this.http.get("/webhooks/endpoints");
    return Array.isArray(data) ? data : data.endpoints ?? [];
  }

  async createWebhook(url: string, events: string[]): Promise<Webhook> {
    const { data } = await this.http.post("/webhooks/endpoints", { url, events });
    return data;
  }

  async deleteWebhook(webhookId: string): Promise<{ success: boolean }> {
    await this.http.delete(`/webhooks/endpoints/${webhookId}`);
    return { success: true };
  }

  // ── Zoom Annotations (local, session-scoped) ─────────────────────────────

  addZoomAnnotation(annotation: ZoomAnnotation): ZoomAnnotation {
    const existing = this.zoomAnnotations.get(annotation.video_id) ?? [];
    existing.push(annotation);
    this.zoomAnnotations.set(annotation.video_id, existing);
    return annotation;
  }

  getZoomAnnotations(videoId: string): ZoomAnnotation[] {
    return this.zoomAnnotations.get(videoId) ?? [];
  }

  clearZoomAnnotations(videoId: string): { cleared: number } {
    const count = (this.zoomAnnotations.get(videoId) ?? []).length;
    this.zoomAnnotations.delete(videoId);
    return { cleared: count };
  }

  exportZoomScript(videoId: string): string {
    const annotations = this.zoomAnnotations.get(videoId) ?? [];
    if (annotations.length === 0) return "// No zoom annotations for this video.";
    const lines = annotations.map((a, i) =>
      `// Step ${i + 1} @ ${a.timestamp_seconds}s — Zoom ${a.zoom_level}x at (${a.x}%, ${a.y}%) ${a.label ? `[${a.label}]` : ""}`
    );
    return [
      `// Tella Zoom Script — Video: ${videoId}`,
      `// Generated by tella-tv-mcp-server`,
      "",
      ...lines,
    ].join("\n");
  }
}
